---
#
# tasks file for ansible-role-ansible
#
# vim:et:ts=2:ft=ansible

- name: Install dependencies via APT
  ansible.builtin.apt:
    state: present
    name:
      - "{{ 'python-pip' if ansible_distribution_version in ['14.04', '18.04'] else 'python3-pip' }}"
      - "{{ 'python-dev' if ansible_distribution_version in ['14.04', '18.04'] else 'python3-dev' }}"
      - libffi-dev
      - libssl-dev

- name: Install Ansible and dependencies via PIP
  ansible.builtin.pip:
    name:
      - "MarkupSafe{{ _ansible.markupsafe_version | default('') }}"
      - netaddr
      - boto
      - boto3
      - passlib
      - "Jinja2{{ _ansible.jinja2_version | default('') }}"
      - "ansible{{ _ansible.ansible_version | default('') }}"
