---
- name: Install Ansible and dependencies via PIP
  ansible.builtin.pip:
    name:
      # Required for deb822_repository
      - python-debian
      - netaddr
      - boto3
      - botocore
      # required for xml parsing
      - lxml
      - passlib
      # Required for Postgres
      - psycopg2-binary
      # Required for MySQL
      - PyMySQL
      # Required for different Ansible modules
      - requests
      - wheel
      - "ansible-core{{ _ansible.ansible_version | default('') }}"
    virtualenv_command: /usr/bin/python3.12 -m venv
    virtualenv: /opt/ansible_virtualenv

- name: Create symbolic links
  ansible.builtin.file:
    src: "/opt/ansible_virtualenv/bin/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    owner: root
    group: root
    state: link
  loop:
    - ansible
    - ansible-config
    - ansible-connection
    - ansible-console
    - ansible-doc
    - ansible-galaxy
    - ansible-inventory
    - ansible-playbook
    - ansible-pull
    - ansible-test
    - ansible-vault