---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update APT Cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      register: result
      until: result is succeeded
      when: ansible_os_family == 'Debian'

    - name: Add Deadsnakes APT repository
      ansible.builtin.apt_repository:
        repo: ppa:deadsnakes/ppa

    - name: Install python3.12 via APT
      ansible.builtin.apt:
        state: present
        update_cache: true
        name:
          - python3.12
          - python3.12-dev
          - python3.12-venv

    - name: Install python3-pip via APT
      ansible.builtin.apt:
        state: present
        name: python3-pip

  tasks:
    - name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      ansible.builtin.include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
