name: Run yamllint on ASPs

on: [push]

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install yamllint
        run: sudo apt-get --yes install yamllint
      - name: 'Lint the YAML as a Service :)'
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: '.'
          yamllint_config_filepath: 'galaxy-yamllint.yaml'
          yamllint_strict: true
          yamllint_comment: false



